### ISSUE TITLE
Are you Twitter.com owner?

### ISSUE THREAD

**Issue by daichikuwa0618** [Xx0w0wxX/Xx0w0wxX#1]
No twitter account on your profile README and I just get jumped into [Twitter.com](https://twitter.com).

If you have any Twitter accounts and you're not a man who don't want to open Twitter account, I recommend you attach it like this:

```html
Contact me on <a href="https://twitter.com/your_account_id">Twitter</a>
```

Otherwise, that line has no necessity, I guess.

https://github.com/Xx0w0wxX/Xx0w0wxX/blob/master/README.md#L10

**Comment by Xx0w0wxX** [comment]
Actually, I own Twitter itself.

**Comment by daichikuwa0618** [comment]
Okey, **if so**, no problems...

**Comment by Xx0w0wxX** [comment]
close #1

good point!
